# OTA assert
TARGET_OTA_ASSERT_DEVICE := LGMS330,LG-K330,m1

# Device init
TARGET_INIT_VENDOR_LIB := libinit_m1
TARGET_LIBINIT_DEFINES_FILE := $(DEVICE_PATH)/init/init_m1.cpp

# Device unified
TARGET_UNIFIED_DEVICE := true
